application: nextferry
module: default
version: 4
runtime: python27
instance_class: B1
api_version: 1
threadsafe: true
manual_scaling:
   instances: 1

handlers:
- url: /tasks/.*
  script: Server.app
  login: admin
- url: /.*
  script: Server.app

inbound_services:
- mail



